version: '3.9'

services:
  EnviarEmailDoBDRPAParaAssinaturaD4signTask:
    image: enviaremaildodbparaassinaturad4signtask
    hostname: EnviarEmailDoBDPAParaAssinaturaD4signTask
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - TOPIC=EnviarEmailDoBDRPAParaAssinaturaD4signTask
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ENG_REST_URL=${CAMUNDA_URL}
      - ENG_REST_USERNAME=${CAMUNDA_USERNAME}
      - ENG_REST_PASSWORD=${CAMUNDA_PASSWORD}
      - MAX_TASK_DURATION=30000
      - D4SIGN_URL=${D4SIGN_URL}
      - D4SIGN_TOKEN=${D4SIGN_TOKEN}
      - D4SIGN_KEY=${D4SIGN_KEY}
      - D4SIGN_HMAC_KEY=${D4SIGN_HMAC_KEY}
      - D4SIGN_SAFE=RPA
    volumes:
      - ${ACS_DOCS_PATH}/GerenciaContratosDeRPAProcess/outputs:/home/appuser/outputs:ro

networks:
  default:
    external: true
    name: backend
